### PR TITLE
Use a more reliable source of the static files URL

### PR DESCRIPTION
**Pull request by illia-v**
I have a case when SQL explorer pages don't render correctly because paths of all static files are wrong.

django-storages is used and [`AWS_LOCATION`](https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html#:~:text=location%20or%20AWS_LOCATION) is set, so actual paths are prefixed.
The SQL explorer uses `settings.STATIC_URL` to construct URLs of static files, but `settings.STATIC_URL` doesn't contain the prefix in the described configuration.

There may be other cases when storage classes change URLs, let's build the URLs using a configured Django storage.

### CODE REVIEW

**Comment by chrisclark** [comment]
Love this! Thank you.

I have struggled to get all of the various django static stuff to be really solid, and I think this helps. I will review shortly, merge, and get a beta release out by the end of this week (along with a bunch of other improvements). I'll get it tested in a more complex environment next week and hopefully have a final release done by Aug 2.

**Comment by illia-v** [comment]
@chrisclark thank you for reviewing this and providing the expected release date!

**Comment by chrisclark** [comment]
@illia-v FYI 5.1b1 is on pypi:
https://pypi.org/project/django-sql-explorer/5.1b1/

Will try to cut a final release sometime in the coming week.

**Comment by chrisclark** [comment]
I have tested this on demo.sqlexplorer.io, with similar django-storages settings:

https://github.com/explorerhq/demo-site/blob/master/explorer_demo/settings.py

And it seems to be working well. I will cut a release tomorrow after one more round of testing in another environment.

**Pull request merged**
